apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rhtap-quarkus-app-1
  janus-idp.io/tekton: rhtap-quarkus-app-1
  backstage.io/kubernetes-id: rhtap-quarkus-app-1
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rhtap-quarkus-app-1
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
